name: Run quality checks
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev
      # - release
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Composer install
        run: "composer install"

      - name: Run code sniffer
        run: "composer run lint"

      - name: Run swagger check
        run: php artisan l5-swagger:generate

      - name: Run static analysis
        run: "composer run phpstan"

      - name: Run unit tests
        env:
          APP_ENV: "testing"
          KEYCLOAK_ALLOWED_RESOURCES: ${{ secrets.KEYCLOAK_ALLOWED_RESOURCES }}
          KEYCLOAK_BASE_URL: ${{ secrets.KEYCLOAK_BASE_URL }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          KEYCLOAK_LOAD_USER_FROM_DATABASE: ${{ secrets.KEYCLOAK_LOAD_USER_FROM_DATABASE }}
          KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
          KEYCLOAK_REALM_PUBLIC_KEY: ${{ secrets.KEYCLOAK_REALM_PUBLIC_KEY }}
          KEYCLOAK_SERVICE_PASSWORD: ${{ secrets.KEYCLOAK_SERVICE_PASSWORD }}
          KEYCLOAK_SERVICE_USERNAME: ${{ secrets.KEYCLOAK_SERVICE_USERNAME }}
          KEYCLOAK_TEST_PASSWORD: ${{ secrets.KEYCLOAK_TEST_PASSWORD }}
          KEYCLOAK_TEST_USERNAME: ${{ secrets.KEYCLOAK_TEST_USERNAME }}
          RULES_ENGINE_SERVICE: ${{ secrets.RULES_ENGINE_SERVICE }}
          RULES_ENGINE_PROJECT_ID: ${{ secrets.RULES_ENGINE_PROJECT_ID }}
          RULES_ENGINE_DOCUMENT_ID: ${{ secrets.RULES_ENGINE_DOCUMENT_ID }}
          RULES_ENGINE_PROJECT_TOKEN: ${{ secrets.RULES_ENGINE_PROJECT_TOKEN }}
          RULES_ENGINE_EVAL_MODEL: ${{ secrets.RULES_ENGINE_EVAL_MODEL }}
        run: "composer run pest"
